default:
  image: ruby:2.6.3

before_script:
  - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
  - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
  - wget -O- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update
  - apt-get install -y heroku-toolbelt yarn
  - gem install dpl

stages:
  - production

deploy-production:
  stage: production
  environment: production
  when: manual
  allow_failure: true
  script:
    - dpl --provider=heroku --app=voyce --api-key=$HEROKU_PRODUCTION_API_KEY
    - bundle install
    - yarn install
    - rake assets:precompile
    - heroku run rake db:migrate --exit-code --app=voyce --api-key=$HEROKU_PRODUCTION_API_KEY