stages:
  - production
deploy-production:
  stage: production
  environment: production
  variables:
    HEROKU_API_KEY: $HEROKU_STAGING_API_KEY
  tags:
    - deploymen
  when: manual
  allow_failure: true
  script:
    - dpl --provider=heroku --app=staging-formulariocontato --api-key=$HEROKU_API_KEY