version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5050:5050"
    depends_on:
      - db
  web:
    tty: true
    stdin_open: true
    build: ./
    container_name: application
    privileged: true
    volumes:
      - ~/.ssh/:/home/docker/.ssh/
      - ../:/var/www/html/voyce
    environment:
      RAILS_MASTER_KEY: 34d098235bdacb6f9f11e881d1692c53
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - db
