version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: ./
    container_name: application
    privileged: true
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/www/html/voyce/config/voyce-adminsdk.json
    volumes:
      - ../:/var/www/html/voyce
    ports:
      - "3000:3000"
      - "80:80"
